/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Cheng
 */
public class ChangePasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChangePasswordPanel
     */
    public ChangePasswordPanel() {
        initComponents();
        jcbRecoverQues.setEnabled(false);
        jtfRecoverAns.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblOld = new javax.swing.JLabel();
        jtfOldPass = new javax.swing.JPasswordField();
        jtfNewPass = new javax.swing.JPasswordField();
        jtfConfirmPass = new javax.swing.JPasswordField();
        jchkSetRecQ = new javax.swing.JCheckBox();
        jcbRecoverQues = new javax.swing.JComboBox<>();
        jtfRecoverAns = new javax.swing.JTextField();
        jlblRecoveryA = new javax.swing.JLabel();
        jlblRecoveryQ = new javax.swing.JLabel();
        jbtConfirm = new java.awt.Button();
        jlblConfirm = new javax.swing.JLabel();
        jlblNew = new javax.swing.JLabel();

        setBackground(new java.awt.Color(209, 169, 149));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblOld.setText("Old Password :");
        add(jlblOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
        add(jtfOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 180, -1));
        add(jtfNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 180, -1));
        add(jtfConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, -1));

        jchkSetRecQ.setBackground(new java.awt.Color(209, 169, 149));
        jchkSetRecQ.setText("Set new recovery question and answer");
        jchkSetRecQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSetRecQActionPerformed(evt);
            }
        });
        add(jchkSetRecQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jcbRecoverQues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your first pet's name?", "What is your favourite colour?", "Where is your hometown?" }));
        add(jcbRecoverQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, -1));
        add(jtfRecoverAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 180, -1));

        jlblRecoveryA.setText("Recovery Answer   : ");
        add(jlblRecoveryA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jlblRecoveryQ.setText("Recovery Question : ");
        add(jlblRecoveryQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jbtConfirm.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jbtConfirm.setLabel("Confirm");
        add(jbtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 70, -1));

        jlblConfirm.setText("Confirm New Password :");
        add(jlblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jlblNew.setText("New Password :");
        add(jlblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jchkSetRecQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSetRecQActionPerformed
        // TODO add your handling code here:
        
        if(jchkSetRecQ.isSelected()==true){
            jcbRecoverQues.setEnabled(true);
            jtfRecoverAns.setEnabled(true);
        }
        else {
            jtfRecoverAns.setText("");
            jcbRecoverQues.setEnabled(false);
            jtfRecoverAns.setEnabled(false);  

        
        }
    }//GEN-LAST:event_jchkSetRecQActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jbtConfirm;
    private javax.swing.JComboBox<String> jcbRecoverQues;
    private javax.swing.JCheckBox jchkSetRecQ;
    private javax.swing.JLabel jlblConfirm;
    private javax.swing.JLabel jlblNew;
    private javax.swing.JLabel jlblOld;
    private javax.swing.JLabel jlblRecoveryA;
    private javax.swing.JLabel jlblRecoveryQ;
    private javax.swing.JPasswordField jtfConfirmPass;
    private javax.swing.JPasswordField jtfNewPass;
    private javax.swing.JPasswordField jtfOldPass;
    private javax.swing.JTextField jtfRecoverAns;
    // End of variables declaration//GEN-END:variables
}
