/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JPanel;

/**
 *
 * @author lysan
 */
public class DefaultPanel extends javax.swing.JPanel {

    /**
     * Creates new form DefaultPanel
     */
    public JPanel getJpAddUpdate() {
        return this;
    }

    public JPanel getJpSearch() {
        return this;
    }
    public DefaultPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblSupportInfo = new javax.swing.JLabel();
        jlblBanner = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSupportInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlblSupportInfo.setText("For product support, email at support@vetclinicsystem.com");
        add(jlblSupportInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jlblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Default.png"))); // NOI18N
        jlblBanner.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jlblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 800, 400));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("               ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 50, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlblBanner;
    private javax.swing.JLabel jlblSupportInfo;
    // End of variables declaration//GEN-END:variables
}
