/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.MaintainCustomer;
import domain.CreditCard;
import domain.Customer;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import control.MaintainCreditCard;
import java.awt.datatransfer.*;
import java.awt.Toolkit;

/**
 *
 * @author Cheng
 */
public class ManageCreditCardDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddCreditCardDialog
     */
    MaintainCustomer custControl;
    MaintainCreditCard creditControl;
    private static CreditCard card;
    
    public ManageCreditCardDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        custControl = new MaintainCustomer();
        creditControl = new MaintainCreditCard();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblCCNum = new javax.swing.JLabel();
        jtfCCNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlblAgent = new javax.swing.JLabel();
        jmcMonth = new com.toedter.calendar.JMonthChooser();
        jycYear = new com.toedter.calendar.JYearChooser();
        jcbAgent = new javax.swing.JComboBox<>();
        jlblCvc = new javax.swing.JLabel();
        jtfCvc = new javax.swing.JTextField();
        jlblHolder = new javax.swing.JLabel();
        jtfHolder = new javax.swing.JTextField();
        jlblName = new javax.swing.JLabel();
        jlblCustIC = new javax.swing.JLabel();
        jtfCustIC = new javax.swing.JTextField();
        jbtAdd = new javax.swing.JButton();
        jcbCardName = new javax.swing.JComboBox<>();
        jbtSearch = new javax.swing.JButton();
        jbtModify = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jbtClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Credit Card - ");
        setIconImage(Toolkit.getDefaultToolkit().getImage(LoginFrame.class.getResource("/images/logo.png")));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCCNum.setText("Credit Card No. :");
        getContentPane().add(jlblCCNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(jtfCCNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, -1));

        jLabel1.setText("Expiry Date :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jlblAgent.setText("Issuing Agent :");
        getContentPane().add(jlblAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(jmcMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));
        getContentPane().add(jycYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jcbAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MasterCard", "Visa" }));
        getContentPane().add(jcbAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jlblCvc.setText("CVC :");
        getContentPane().add(jlblCvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(jtfCvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 40, -1));

        jlblHolder.setText("Card Holder Name :");
        getContentPane().add(jlblHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        getContentPane().add(jtfHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 180, -1));

        jlblName.setText("Card Name :");
        getContentPane().add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jlblCustIC.setText("Customer IC :");
        getContentPane().add(jlblCustIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));
        getContentPane().add(jtfCustIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 110, -1));

        jbtAdd.setText("Add");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jcbCardName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alliance Bank Malaysia Berhad", "AmBank (M) Berhad", "Bank of China (Malaysia) Berhad", "CIMB Bank Berhad", "HSBC Bank Malaysia Berhad", "Hong leong Bank Berhad", "OCBC Bank (Malaysia) Berhad", "Public Bank Berhad", "RHB Bank Berhad", "United Overseas Bank (Malaysia) Bhd.", " " }));
        getContentPane().add(jcbCardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 180, -1));

        jbtSearch.setText("Search ");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jbtModify.setText("Modify");
        jbtModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jbtClose.setText("Use This Card");
        jbtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 70, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Manage Credit Card");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 100, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        // TODO add your handling code here:
        String ccNum = jtfCCNum.getText();
        String holder = jtfHolder.getText();
        int month = jmcMonth.getMonth();
        int year = jycYear.getYear(); 
        Calendar cal = Calendar.getInstance();
        cal.set(year, month, 1);
        Date date = cal.getTime();
        String cardName = (String)jcbCardName.getSelectedItem();
        String custIC = jtfCustIC.getText();
        String agent = (String)jcbAgent.getSelectedItem();
        String cvc = jtfCvc.getText();
        
        Customer customer = custControl.searchRecord(custIC);
        CreditCard cc = new CreditCard(ccNum,date,agent,cvc,holder,cardName,customer);
        
        if(cc!=null){
         //write to database
                CreditCard c = creditControl.searchRecord(cc.getCcNum());
                
                if(c != null)
                {
                    JOptionPane.showMessageDialog(null,"This credit card already exist.", "Duplicate Record", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    c = cc;
                    try{
                    creditControl.addRecord(c);
                    resetFields();
                    setCard(c);
                    JOptionPane.showMessageDialog(null,"New credit card for "+customer.getCustName()+" has been added. ","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch (Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                    }
                }  
                
        }
        else{
            int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
//                resetFields();
            }              
        }  
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        // TODO add your handling code here:
                String ccNum = jtfCCNum.getText();
                CreditCard c = creditControl.searchRecord(ccNum);
                
                if(c != null)
                {

                    jtfCCNum.setText(c.getCcNum());
                    jtfHolder.setText(c.getCardHolderName());
                    Date date = c.getCcExpiryDate();
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    jmcMonth.setMonth(cal.get(Calendar.MONTH));
                    jycYear.setYear(cal.get(Calendar.YEAR));
                    jcbCardName.setSelectedItem(c.getCardName());
                    jtfCustIC.setText(c.getCustomer().getCustIC());
                    jcbAgent.setSelectedItem(c.getIssuingAgent());
                    jtfCvc.setText(c.getCvc());
                    setCard(c);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"This credit card number does not exist","Record not found",JOptionPane.ERROR_MESSAGE);
                }
               
           
    }//GEN-LAST:event_jbtSearchActionPerformed

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        // TODO add your handling code here:
        String ccNum = jtfCCNum.getText();
        CreditCard c = creditControl.searchRecord(ccNum);
                
        if(c != null)
                {
                    jtfCCNum.setText(c.getCcNum());
                    jtfHolder.setText(c.getCardHolderName());
                    Date date = c.getCcExpiryDate();
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    jmcMonth.setMonth(cal.get(Calendar.MONTH));
                    jycYear.setYear(cal.get(Calendar.YEAR));
                    jcbCardName.setSelectedItem(c.getCardName());
                    jtfCustIC.setText(c.getCustomer().getCustIC());
                    jcbAgent.setSelectedItem(c.getIssuingAgent());
                    jtfCvc.setText(c.getCvc());
                    
                    int option = JOptionPane.showConfirmDialog(null,"Are you sure to DELETE ?");
                    if(option == JOptionPane.YES_OPTION)
                    {
                        creditControl.deleteRecord(ccNum);
                        resetFields();
                        JOptionPane.showMessageDialog(null,"Record deleted ");
                        
                    }
                }
                    else
                {
                    JOptionPane.showMessageDialog(null,"This credit card does not exist","Record not found",JOptionPane.ERROR_MESSAGE);
                }
            
    }//GEN-LAST:event_jbtDeleteActionPerformed

    private void jbtModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifyActionPerformed
        // TODO add your handling code here:
         String ccNum = jtfCCNum.getText();
         CreditCard c = creditControl.searchRecord(ccNum);
        
         if(c != null)
                {
                  
                    c.setCcNum(jtfCCNum.getText());
                    c.setCardHolderName(jtfHolder.getText());
                    
                    int month = jmcMonth.getMonth();
                    int year = jycYear.getYear();
                    Calendar cal = Calendar.getInstance();
                    cal.set(year, month, 1);
                    Date date = cal.getTime();
                    c.setCcExpiryDate(date);
                    c.setCardName((String)jcbCardName.getSelectedItem());
                    c.getCustomer().setCustIC(jtfCustIC.getText());
                    c.setIssuingAgent((String)jcbAgent.getSelectedItem());
                    c.setCvc(jtfCvc.getText());
                    creditControl.updateRecord(c);
                    resetFields();
                    setCard(c);
                    JOptionPane.showMessageDialog(null,"Record Updated.");
                    
                }
                else 
                {
                    JOptionPane.showMessageDialog(null,"This credit card does not exist","Record not found",JOptionPane.ERROR_MESSAGE);
                }
            
    }//GEN-LAST:event_jbtModifyActionPerformed

    private void jbtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCloseActionPerformed
        // TODO add your handling code here:
        
        String ccnum =jtfCCNum.getText();
        StringSelection strSelection = new StringSelection(ccnum);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(strSelection, strSelection);
        dispose();
    }//GEN-LAST:event_jbtCloseActionPerformed

    private void resetFields(){
        jtfCCNum.setText("");
        jtfHolder.setText("");
        jmcMonth.setMonth(1);
        jycYear.setYear(2016);
        jcbCardName.setSelectedIndex(0);
        jtfCustIC.setText("");
        jcbAgent.setSelectedIndex(0);
        jtfCvc.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCreditCardDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCreditCardDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCreditCardDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCreditCardDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageCreditCardDialog dialog = new ManageCreditCardDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        PaymentPanel.setCreditcard(card);
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtClose;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JButton jbtModify;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JComboBox<String> jcbAgent;
    private javax.swing.JComboBox<String> jcbCardName;
    private javax.swing.JLabel jlblAgent;
    private javax.swing.JLabel jlblCCNum;
    private javax.swing.JLabel jlblCustIC;
    private javax.swing.JLabel jlblCvc;
    private javax.swing.JLabel jlblHolder;
    private javax.swing.JLabel jlblName;
    private com.toedter.calendar.JMonthChooser jmcMonth;
    private javax.swing.JTextField jtfCCNum;
    private javax.swing.JTextField jtfCustIC;
    private javax.swing.JTextField jtfCvc;
    private javax.swing.JTextField jtfHolder;
    private com.toedter.calendar.JYearChooser jycYear;
    // End of variables declaration//GEN-END:variables

    public static void setCard(CreditCard card) {
        ManageCreditCardDialog.card = card;
    }
}
