
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.MaintainStaff;
import  domain.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Cheng
 */
public class PasswordRecoveryDialog extends javax.swing.JDialog {

    /**
     * Creates new form PasswordRecoveryDialog
     */
    MaintainStaff staffControl;
    Staff staff;
    
    public PasswordRecoveryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        staffControl = new MaintainStaff();
        
    }

    public void resetFields(){
    
    jtfRecoverAns.setText("");
    jtfUsername.setText("");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jcbRecoverQues = new javax.swing.JComboBox<>();
        jtfRecoverAns = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtNext = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtConfirm = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jpfConfirm = new javax.swing.JPasswordField();
        jpfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Password Recovery");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbRecoverQues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your first pet's name?", "What is your favourite colour?", "Where is your hometown?" }));
        jPanel3.add(jcbRecoverQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 170, -1));

        jtfRecoverAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRecoverAnsActionPerformed(evt);
            }
        });
        jPanel3.add(jtfRecoverAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, -1));

        jLabel1.setText(" Username : ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 70, -1));

        jLabel2.setText("Recovery Answer   : ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jbtNext.setText("Next");
        jbtNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtNextMouseClicked(evt);
            }
        });
        jbtNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNextActionPerformed(evt);
            }
        });
        jPanel3.add(jbtNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jbtCancel.setText("Cancel");
        jbtCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtCancelMouseClicked(evt);
            }
        });
        jPanel3.add(jbtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel3.setText("Please choose your recovery question and enter your answer: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, -1));

        jLabel7.setText("Recovery Question : ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jPanel1.add(jPanel3, "card3");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("New Password :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel5.setText("Confirm New Password :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jbtConfirm.setText("Confirm");
        jbtConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtConfirmMouseClicked(evt);
            }
        });
        jPanel2.add(jbtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jButton4.setText("Back");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jpfConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfConfirmActionPerformed(evt);
            }
        });
        jPanel2.add(jpfConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, -1));
        jPanel2.add(jpfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, -1));

        jPanel1.add(jPanel2, "card2");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNextActionPerformed
        // TODO add your handling code here:
        //add check password method here

    }//GEN-LAST:event_jbtNextActionPerformed

    private void jtfRecoverAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRecoverAnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRecoverAnsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
       
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();
            
        //Adding Pannel
        jPanel1.add(jPanel3);
        jPanel1.repaint();
        jPanel1.revalidate();
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameActionPerformed

    private void jbtCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtCancelMouseClicked

    private void jbtNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtNextMouseClicked
        // TODO add your handling code here:
        if (validateAnswer()==true){
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
        //Adding Pannel
            jPanel1.add(jPanel2);
            jPanel1.repaint();
            jPanel1.revalidate();
        
        }
        else{
            JOptionPane.showMessageDialog(null,"Username not found or incorrect recovery answer. Please try again.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtNextMouseClicked

    private void jbtConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtConfirmMouseClicked
        // TODO add your handling code here:
        String password = String.copyValueOf(jpfPass.getPassword());
        String confirm = String.copyValueOf(jpfConfirm.getPassword());
        
        
        if(password.equals(confirm)){
            try{
            this.staff.setPassword(PasswordHash.createHash(password));
            staffControl.updateRecordPassword(staff);
            }
            catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null,"Password successfully reset!","Success!",JOptionPane.INFORMATION_MESSAGE);

        }
        else{
            JOptionPane.showMessageDialog(null,"Passwords do not match. Please try again.","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        jpfPass.setText("");
        jpfConfirm.setText("");
        
    }//GEN-LAST:event_jbtConfirmMouseClicked

    private void jpfConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfConfirmActionPerformed

    public boolean validateAnswer(){
        String username = jtfUsername.getText();
        String question = (String)jcbRecoverQues.getSelectedItem();
        String answer = jtfRecoverAns.getText();
        boolean valid = false;
        
        switch(question){
             case "What is your first pet's name?"  : 
                answer="p"+answer;
                break;
             case "What is your favourite colour?"  : 
                answer="c"+answer;
                break;
             case "Where is your hometown?"         :
                 answer="h"+answer;
                break;
         }
        
        staff = staffControl.searchRecord(username);
        
        if(staff != null){
             valid = staff.getSecurityAns().equalsIgnoreCase(answer);
        }

        
        return valid;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordRecoveryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordRecoveryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordRecoveryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordRecoveryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasswordRecoveryDialog dialog = new PasswordRecoveryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtConfirm;
    private javax.swing.JButton jbtNext;
    private javax.swing.JComboBox<String> jcbRecoverQues;
    private javax.swing.JPasswordField jpfConfirm;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextField jtfRecoverAns;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
