/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.MaintainPet;
import domain.Customer;
import domain.Pet;
import java.awt.Color;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class PetPanel extends javax.swing.JPanel {

    
    MaintainPet petControl;
    
    /**
     * Creates new form Pet
     */
    public PetPanel() {
        initComponents();
        petControl = new MaintainPet();
        jTextField1.setOpaque(false);
        jTextField1.setBackground(new Color(255,255,255,127));
        jTextField1.setBorder(null);        
        setDynamicPanel();
    }
    
    public Pet validateInput(){
    
    Pet pet;
    boolean valid =true; 
    
    String breed = jtfBreed.getText();
    Double height = Double.parseDouble(jtfHeight.getText());
    Double length = Double.parseDouble(jtfLength.getText());
    String owneric = jtfOwnerIc.getText();
    String petid = jtfPetId.getText();
    String petname = jtfPetName.getText();
    Double weight = Double.parseDouble(jtfWeight.getText());
    
    valid = breed.equals(null)?false:true; //need
    valid = height.equals(null)?false:true;
    valid = length.equals(null)?false:true;
    valid = petid.equals(null)?false:true;
    valid = petname.equals(null)?false:true;
    valid = weight.equals(null)?false:true;
    if(!Pattern.matches("\\d{12}", owneric)){valid =false;} 
    
    if(valid==true){
          
        Customer customer = new Customer();
        customer.setCustIC(owneric);
           pet = new Pet(petid,petname,height,weight,length,(String)jcbType.getSelectedItem(),breed,new Date(),(char)jcbGender.getSelectedItem(),customer);
    }
    else {
             pet=null;
    }
         
         return pet;
    }
    
    public void resetFields(){
    
    jtfBreed.setText("");
    jtfHeight.setText("");
    jtfLength.setText("");
    jtfOwnerIc.setText("");
    jtfPetId.setText("");
    jtfPetName.setText("");
    jtfWeight.setText("");
    }
    
    public void setDynamicPanel() {
        JPanel targetPanel = new JPanel();
        if(MainMenu.action.equals("add")){
             targetPanel=jpAdd;
        }
        else if (MainMenu.action.equals("search")){
            targetPanel=jpSearch;
        }
        
        dynamicPanel.removeAll();
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
            
        //Adding Pannel
        dynamicPanel.add(targetPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        dynamicPanel = new javax.swing.JPanel();
        jpAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfPetId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPetName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfHeight = new javax.swing.JTextField();
        jtfLength = new javax.swing.JTextField();
        jtfBreed = new javax.swing.JTextField();
        jcbGender = new javax.swing.JComboBox<>();
        jtfWeight = new javax.swing.JTextField();
        jtfOwnerIc = new javax.swing.JTextField();
        jbtAddPet = new javax.swing.JButton();
        jdpBirthDate = new com.toedter.calendar.JDateChooser();
        jpSearch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 260, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        dynamicPanel.setLayout(new java.awt.CardLayout());

        jpAdd.setBackground(new java.awt.Color(255, 255, 204));
        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Pet ID :");
        jpAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jtfPetId.setToolTipText("Enter pet ID");
        jpAdd.add(jtfPetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 90, -1));

        jLabel3.setText("Pet Name :");
        jpAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jtfPetName.setToolTipText("Enter pet name");
        jtfPetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPetNameActionPerformed(evt);
            }
        });
        jpAdd.add(jtfPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 90, -1));

        jLabel4.setText("Pet Height :");
        jpAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel5.setText("Pet Weight :");
        jpAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel6.setText("Pet Length :");
        jpAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel7.setText("Animal Type :");
        jpAdd.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel8.setText("Breed :");
        jpAdd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        jcbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canine", "Feline", "Aquatic", "Reptile", "Avian" }));
        jpAdd.add(jcbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel9.setText("Pet Birth Date :");
        jpAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel10.setText("Pet Gender :");
        jpAdd.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel11.setText("Owner IC No. :");
        jpAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jtfHeight.setToolTipText("Enter height");
        jpAdd.add(jtfHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 90, -1));

        jtfLength.setToolTipText("Enter length");
        jpAdd.add(jtfLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, -1));

        jtfBreed.setToolTipText("Enter breed");
        jpAdd.add(jtfBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, -1));

        jcbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jpAdd.add(jcbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jtfWeight.setToolTipText("Enter weight");
        jpAdd.add(jtfWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, -1));

        jtfOwnerIc.setToolTipText("Enter NRIC");
        jpAdd.add(jtfOwnerIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 90, -1));

        jbtAddPet.setText("Add Pet");
        jbtAddPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddPetMouseClicked(evt);
            }
        });
        jpAdd.add(jbtAddPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));
        jpAdd.add(jdpBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        dynamicPanel.add(jpAdd, "card3");

        jpSearch.setBackground(new java.awt.Color(255, 255, 204));
        jpSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pet ID", "Name", "Height", "Length", "Animal Type", "Breed", "Birth Date", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jpSearch.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 660, 310));

        jButton5.setText("Modify Pet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jpSearch.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jButton6.setText("Delete Pet");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jpSearch.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        dynamicPanel.add(jpSearch, "card2");

        jPanel1.add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 460));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 526));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jtfPetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPetNameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtAddPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddPetMouseClicked
        // TODO add your handling code here:
        Pet pet = validateInput();
        if(pet!=null){
         //write to database
         Pet p = petControl.searchRecord(pet.getPetID());
                
                if(p != null)
                {
                    JOptionPane.showMessageDialog(null,"This pet already exist.", "Duplicate Record", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    p = pet;
                    try{
                    petControl.addRecord(p);
                    resetFields();
                    JOptionPane.showMessageDialog(null,"New pet is created.","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch (Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                    }
                }  
                
         
        }
        else{
            int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
                resetFields();
            }              
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddPetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtAddPet;
    private javax.swing.JComboBox<String> jcbGender;
    private javax.swing.JComboBox<String> jcbType;
    private com.toedter.calendar.JDateChooser jdpBirthDate;
    private javax.swing.JPanel jpAdd;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JTextField jtfBreed;
    private javax.swing.JTextField jtfHeight;
    private javax.swing.JTextField jtfLength;
    private javax.swing.JTextField jtfOwnerIc;
    private javax.swing.JTextField jtfPetId;
    private javax.swing.JTextField jtfPetName;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
}
