/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Cheng
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblReportType = new javax.swing.JLabel();
        jcbReportType = new javax.swing.JComboBox<>();
        jlblStart = new javax.swing.JLabel();
        jlblEnd = new javax.swing.JLabel();
        jdpStartDate = new com.toedter.calendar.JDateChooser();
        jdpEndDate = new com.toedter.calendar.JDateChooser();
        jbtGenerateReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(227, 234, 254));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblReportType.setText("Report Type :");
        add(jlblReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jcbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transaction Detail", "Treatment Exception", "Customer Summary", "Services Summary" }));
        add(jcbReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, -1));

        jlblStart.setText("Start Date :");
        add(jlblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jlblEnd.setText("  End Date :");
        add(jlblEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));
        add(jdpStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, -1));
        add(jdpEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, -1));

        jbtGenerateReport.setText("Generate Report");
        jbtGenerateReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtGenerateReportMouseClicked(evt);
            }
        });
        add(jbtGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGenerateReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtGenerateReportMouseClicked
        // TODO add your handling code here:
        // event handler for button

       String host = "jdbc:derby://localhost:1527/vetdb";
       String user = "nbuser";
       String password = "nbuser";
       Connection conn = null;
       
       String reportSource = "src/reportTemplates/TransactionDetail.jrxml"; 

       Map<String, Object> params = new HashMap<String, Object>(); 

       try    {	 
         Class.forName("org.apache.derby.jdbc.ClientDriver");
         conn = DriverManager.getConnection(host, user, password);
               JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

      JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, conn);
      JasperViewer.viewReport(jasperPrint, false); 
        

      } catch (JRException jrex) {
            JOptionPane.showMessageDialog(this, "Error in generating report");
  	      jrex.printStackTrace();
      }  catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Unble to generate report~!");
	      ex.printStackTrace();
      }


    }//GEN-LAST:event_jbtGenerateReportMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtGenerateReport;
    private javax.swing.JComboBox<String> jcbReportType;
    private com.toedter.calendar.JDateChooser jdpEndDate;
    private com.toedter.calendar.JDateChooser jdpStartDate;
    private javax.swing.JLabel jlblEnd;
    private javax.swing.JLabel jlblReportType;
    private javax.swing.JLabel jlblStart;
    // End of variables declaration//GEN-END:variables
}
