/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Cheng
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblReportType = new javax.swing.JLabel();
        jcbReportType = new javax.swing.JComboBox<>();
        jlblStart = new javax.swing.JLabel();
        jlblEnd = new javax.swing.JLabel();
        jdcStart = new com.toedter.calendar.JDateChooser();
        jdcEnd = new com.toedter.calendar.JDateChooser();
        jbtGenerate = new javax.swing.JButton();

        setBackground(new java.awt.Color(227, 234, 254));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblReportType.setText("Report Type :");
        add(jlblReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jcbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transaction Detail", "Treatment Exception", "Customer Summary", "Services Summary" }));
        add(jcbReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, -1));

        jlblStart.setText("Start Date :");
        add(jlblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jlblEnd.setText("  End Date :");
        add(jlblEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));
        add(jdcStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, -1));
        add(jdcEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, -1));

        jbtGenerate.setText("Generate Report");
        add(jbtGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtGenerate;
    private javax.swing.JComboBox<String> jcbReportType;
    private com.toedter.calendar.JDateChooser jdcEnd;
    private com.toedter.calendar.JDateChooser jdcStart;
    private javax.swing.JLabel jlblEnd;
    private javax.swing.JLabel jlblReportType;
    private javax.swing.JLabel jlblStart;
    // End of variables declaration//GEN-END:variables
}
