/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Cheng
 */
public class SchedulePanel extends javax.swing.JPanel {

    /**
     * Creates new form SchedulePanel
     */
        public void setDynamicPanel() {
        JPanel targetPanel = new JPanel();
        if(MainMenu.action.equals("add")){
             targetPanel=jpAdd;
        }
        else if (MainMenu.action.equals("search")){
            targetPanel=jpSearch;
        }
        
        dynamicPanel.removeAll();
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
            
        //Adding Pannel
        dynamicPanel.add(targetPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }
        
    public SchedulePanel() {
        initComponents();
        jtfSearch.setOpaque(false);
        jtfSearch.setBackground(new Color(255,255,255,127));
        jtfSearch.setBorder(null);
        setDynamicPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        dynamicPanel = new javax.swing.JPanel();
        jpSearch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSchedule = new javax.swing.JTable();
        jbtModifySchedule = new javax.swing.JButton();
        jbtDeleteSchedule = new javax.swing.JButton();
        jpAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfStafIc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfTimeSlotNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfCusPhoneNum = new javax.swing.JTextField();
        jtfCusName = new javax.swing.JTextField();
        jdpAppDate = new com.toedter.calendar.JDateChooser();
        jcbHours = new javax.swing.JComboBox<>();
        jcbmins = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jbtAddSchedule = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 260, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 98));

        dynamicPanel.setLayout(new java.awt.CardLayout());

        jpSearch.setBackground(new java.awt.Color(204, 255, 204));
        jpSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Staff IC", "Time Slot Number", "Application Time", "Application Date", "Customer Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtSchedule);

        jpSearch.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 620, 180));

        jbtModifySchedule.setText("Modify Schedule");
        jbtModifySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifyScheduleActionPerformed(evt);
            }
        });
        jpSearch.add(jbtModifySchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jbtDeleteSchedule.setText("Delete Schedule");
        jbtDeleteSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteScheduleActionPerformed(evt);
            }
        });
        jpSearch.add(jbtDeleteSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        dynamicPanel.add(jpSearch, "card2");

        jpAdd.setBackground(new java.awt.Color(204, 255, 204));
        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Staff IC :");
        jpAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jtfStafIc.setToolTipText("Enter staff IC");
        jtfStafIc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStafIcActionPerformed(evt);
            }
        });
        jpAdd.add(jtfStafIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, -1));

        jLabel3.setText("Time Slot Number :");
        jpAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));
        jpAdd.add(jtfTimeSlotNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 100, -1));

        jLabel4.setText("Appointment Time :");
        jpAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setText("Appointment Date :");
        jpAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, -1));

        jLabel6.setText("Customer Phone No. :");
        jpAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 120, -1));

        jLabel7.setText("Customer Name :");
        jpAdd.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, -1));
        jpAdd.add(jtfCusPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 100, -1));
        jpAdd.add(jtfCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));
        jpAdd.add(jdpAppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 100, -1));

        jcbHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jcbHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHoursActionPerformed(evt);
            }
        });
        jpAdd.add(jcbHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jcbmins.setText("hours                minutes");
        jpAdd.add(jcbmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jpAdd.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jbtAddSchedule.setText("Add Schedule");
        jpAdd.add(jbtAddSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        dynamicPanel.add(jpAdd, "card3");

        add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 940, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfStafIcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStafIcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStafIcActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jcbHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHoursActionPerformed

    private void jbtModifyScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifyScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtModifyScheduleActionPerformed

    private void jbtDeleteScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDeleteScheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAddSchedule;
    private javax.swing.JButton jbtDeleteSchedule;
    private javax.swing.JButton jbtModifySchedule;
    private javax.swing.JComboBox<String> jcbHours;
    private javax.swing.JLabel jcbmins;
    private com.toedter.calendar.JDateChooser jdpAppDate;
    private javax.swing.JPanel jpAdd;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JTable jtSchedule;
    private javax.swing.JTextField jtfCusName;
    private javax.swing.JTextField jtfCusPhoneNum;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfStafIc;
    private javax.swing.JTextField jtfTimeSlotNum;
    // End of variables declaration//GEN-END:variables
}
