/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.MaintainSchedule;
import domain.Schedule;
import domain.Staff;
import domain.TableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cheng
 */
public class SchedulePanel extends javax.swing.JPanel {

    
    
        MaintainSchedule scheduleControl;
    /**
     * Creates new form SchedulePanel
     */
        public void setDynamicPanel() {
        JPanel targetPanel = new JPanel();
        if(MainMenu.action.equals("add")){
             targetPanel=jpAdd;
             jbtConfirmChange.setVisible(false);
             jbtConfirmDelete.setVisible(false);
             jbtAddSchedule.setVisible(true);
        }
        else if (MainMenu.action.equals("search")){
            targetPanel=jpSearch;
            jbtDeleteSchedule.setVisible(false);
            jbtModifySchedule.setVisible(false);
        }
        else if(MainMenu.action.equals("modifySelected")){
             targetPanel=jpAdd;
             jbtConfirmChange.setVisible(true);
             jbtConfirmDelete.setVisible(false);
             jbtAddSchedule.setVisible(false);
        
        }else if(MainMenu.action.equals("deleteSelected")){
             targetPanel=jpAdd;
             jbtConfirmChange.setVisible(false);
             jbtConfirmDelete.setVisible(true);
             jbtAddSchedule.setVisible(false);
        }else if(MainMenu.action.equals("modify")){
                targetPanel=jpSearch;
                jbtDeleteSchedule.setVisible(false);
                jbtModifySchedule.setVisible(true);
        }
        else if(MainMenu.action.equals("delete")){
                targetPanel=jpSearch;
                jbtDeleteSchedule.setVisible(true);
                jbtModifySchedule.setVisible(false);
        }
        
        dynamicPanel.removeAll();
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
            
        //Adding Pannel
        dynamicPanel.add(targetPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }
        
         public void fillFields(Schedule schedule){
         
        jtfCusName.setText(schedule.getCustName());
        jtfCusPhoneNum.setText(schedule.getCustPhoneNum());
        jtfStafIc.setText(schedule.getStaffIC());
        jtfTimeSlotNum.setText(""+schedule.getTimeSlotNum());
//        jcbHours.setSelectedItem(schedule.);
//        jcbmins.setSelectedItem(schedule.);
        jdpAppDate.setDate(schedule.getAppDate());
        
         }
        
    public SchedulePanel() {
        initComponents();
        
        scheduleControl = new MaintainSchedule();
        jtfSearch.setOpaque(false);
        jtfSearch.setBackground(new Color(255,255,255,127));
        jtfSearch.setBorder(null);
        setDynamicPanel();
    }

    public Schedule validateInput(){
    
    Schedule schedule;
    boolean valid =true; 
    
    String custName = jtfCusName.getText();
    String custPhoneNum = jtfCusPhoneNum.getText();
    String staffic = jtfStafIc.getText();
    Integer timeSlot = Integer.parseInt(jtfTimeSlotNum.getText());
    
    valid = custName.equals(null)?false:true; //need
    valid = timeSlot.equals(null)?false:true;
    if(!Pattern.matches("\\d{12}", staffic)){valid =false;} // need f got ic
    if(!Pattern.matches("\\d{2,4}-\\d{7,8}", custPhoneNum)){valid =false;} //need if got phone number
    
     if(valid==true){
         schedule=null;
           
         //  schedule = new Schedule(staffic,timeSlot,custName,custPhoneNum);
         }
         else {
             schedule=null;
         }
         
         return schedule;
    }
    
    public void resetFields(){
    
    jtfCusName.setText("");
    jtfCusPhoneNum.setText("");
    jtfSearch.setText("");
    jtfStafIc.setText("");
    jtfTimeSlotNum.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlblSearch = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jlblSchedule = new javax.swing.JLabel();
        dynamicPanel = new javax.swing.JPanel();
        jpSearch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSchedule = new javax.swing.JTable();
        jbtModifySchedule = new javax.swing.JButton();
        jbtDeleteSchedule = new javax.swing.JButton();
        jpAdd = new javax.swing.JPanel();
        jlblIc = new javax.swing.JLabel();
        jtfStafIc = new javax.swing.JTextField();
        jlblTimeSlot = new javax.swing.JLabel();
        jtfTimeSlotNum = new javax.swing.JTextField();
        jlblAppTime = new javax.swing.JLabel();
        jlblAppDate = new javax.swing.JLabel();
        jlblCustPhoneNum = new javax.swing.JLabel();
        jlblCustName = new javax.swing.JLabel();
        jtfCusPhoneNum = new javax.swing.JTextField();
        jtfCusName = new javax.swing.JTextField();
        jdpAppDate = new com.toedter.calendar.JDateChooser();
        jcbHours = new javax.swing.JComboBox<>();
        jlbmins = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jbtAddSchedule = new javax.swing.JButton();
        jbtConfirmChange = new javax.swing.JButton();
        jbtConfirmDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jlblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblSearchMouseClicked(evt);
            }
        });
        jPanel2.add(jlblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 260, 30));

        jlblSchedule.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlblSchedule.setText("Schedule");
        jPanel2.add(jlblSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 98));

        dynamicPanel.setLayout(new java.awt.CardLayout());

        jpSearch.setBackground(new java.awt.Color(204, 255, 204));
        jpSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Staff IC", "Time Slot Number", "Application Time", "Application Date", "Customer Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtSchedule);

        jpSearch.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 620, 180));

        jbtModifySchedule.setText("Modify Schedule");
        jbtModifySchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtModifyScheduleMouseClicked(evt);
            }
        });
        jbtModifySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifyScheduleActionPerformed(evt);
            }
        });
        jpSearch.add(jbtModifySchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jbtDeleteSchedule.setText("Delete Schedule");
        jbtDeleteSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteScheduleActionPerformed(evt);
            }
        });
        jpSearch.add(jbtDeleteSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        dynamicPanel.add(jpSearch, "card2");

        jpAdd.setBackground(new java.awt.Color(204, 255, 204));
        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblIc.setText("Staff IC :");
        jpAdd.add(jlblIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jtfStafIc.setToolTipText("Enter staff IC");
        jtfStafIc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStafIcActionPerformed(evt);
            }
        });
        jpAdd.add(jtfStafIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, -1));

        jlblTimeSlot.setText("Time Slot Number :");
        jpAdd.add(jlblTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));
        jpAdd.add(jtfTimeSlotNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 100, -1));

        jlblAppTime.setText("Appointment Time :");
        jpAdd.add(jlblAppTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jlblAppDate.setText("Appointment Date :");
        jpAdd.add(jlblAppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, -1));

        jlblCustPhoneNum.setText("Customer Phone No. :");
        jpAdd.add(jlblCustPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 120, -1));

        jlblCustName.setText("Customer Name :");
        jpAdd.add(jlblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, -1));
        jpAdd.add(jtfCusPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 100, -1));
        jpAdd.add(jtfCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));
        jpAdd.add(jdpAppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 100, -1));

        jcbHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jcbHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHoursActionPerformed(evt);
            }
        });
        jpAdd.add(jcbHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jlbmins.setText("hours                minutes");
        jpAdd.add(jlbmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jpAdd.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jbtAddSchedule.setText("Add Schedule");
        jbtAddSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddScheduleMouseClicked(evt);
            }
        });
        jbtAddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddScheduleActionPerformed(evt);
            }
        });
        jpAdd.add(jbtAddSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jbtConfirmChange.setText("Confirm Changes");
        jpAdd.add(jbtConfirmChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jbtConfirmDelete.setText("Confirm Delete");
        jbtConfirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmDeleteActionPerformed(evt);
            }
        });
        jpAdd.add(jbtConfirmDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        dynamicPanel.add(jpAdd, "card3");

        add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 940, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfStafIcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStafIcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStafIcActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jcbHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHoursActionPerformed

    private void jbtModifyScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifyScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtModifyScheduleActionPerformed

    private void jbtDeleteScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDeleteScheduleActionPerformed

    private void jbtAddScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddScheduleMouseClicked
        // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddScheduleMouseClicked

    private void jlblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSearchMouseClicked
        // TODO add your handling code here:
        //I used all my 洪荒之力 to make this method 

        jtSchedule.setModel(new DefaultTableModel());
        jtSchedule.repaint();
        
        if(MainMenu.action == "modifySelected"){
            MainMenu.action="modify";
        }
        else if(MainMenu.action == "deleteSelected"){
            MainMenu.action="delete";
        }
        
        String queryStr =jtfSearch.getText();
        int option =0;
        

            if(Pattern.matches("\\d{12}", queryStr)){
                option=1;
            }
           
            else{
                option=2;
            }
            ArrayList<Schedule> scheduleList = scheduleControl.searchRecord(queryStr,option);

    //        MainMenu.action="search";
    //        setDynamicPanel();
            if(scheduleList.size()!=0&&scheduleList!=null){
                Object[][] data = new Object[100][8];
                for(int i=0; i<scheduleList.size();i++){
                data[i] = scheduleList.get(i).getObjects();
                } 
                String[] columnNames = {"Staff IC","Name","Address","Phone No","Position","Qualification"};
                TableModel tModel = new TableModel(data, columnNames);
                jtSchedule.setModel(tModel);  
                jtSchedule.createDefaultColumnsFromModel();
                jtSchedule.repaint();
            }
            else{
                JOptionPane.showMessageDialog(null, "No results found!" , "No such record.", JOptionPane.ERROR_MESSAGE);
            }     
    }//GEN-LAST:event_jlblSearchMouseClicked

    private void jbtModifyScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtModifyScheduleMouseClicked
        // TODO add your handling code here:
        MainMenu.action="modifySelected";
       Schedule selectedSchedule=null;
       if(jtSchedule.getSelectedRow()>=0 ) {
           String ic  = (String) jtSchedule.getValueAt(jtSchedule.getSelectedRow(),0);
           selectedSchedule= scheduleControl.searchRecord(ic);
           if(selectedSchedule!=null){
                setDynamicPanel();
                fillFields(selectedSchedule);
           }
       }
       else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to modify","Empty selection",JOptionPane.ERROR_MESSAGE);
       }

       
    }//GEN-LAST:event_jbtModifyScheduleMouseClicked

    private void jbtAddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddScheduleActionPerformed
        // TODO add your handling code here:
         Schedule schedule = validateInput();
        if(schedule!=null){
         //write to database
         
          Schedule s = scheduleControl.searchRecord(schedule.getStaffIC());
                
                if(s != null)
                {
                    JOptionPane.showMessageDialog(null,"This schedule already exist.", "Duplicate Record", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    s = schedule;
                    try{
                    scheduleControl.addRecord(s);
                    resetFields();
                    JOptionPane.showMessageDialog(null,"New schedule is created.","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch (Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                    }
                }  
        }
        else{
            int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
                resetFields();
            }              
        }          
    }//GEN-LAST:event_jbtAddScheduleActionPerformed

    private void jbtConfirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtConfirmDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAddSchedule;
    private javax.swing.JButton jbtConfirmChange;
    private javax.swing.JButton jbtConfirmDelete;
    private javax.swing.JButton jbtDeleteSchedule;
    private javax.swing.JButton jbtModifySchedule;
    private javax.swing.JComboBox<String> jcbHours;
    private com.toedter.calendar.JDateChooser jdpAppDate;
    private javax.swing.JLabel jlblAppDate;
    private javax.swing.JLabel jlblAppTime;
    private javax.swing.JLabel jlblCustName;
    private javax.swing.JLabel jlblCustPhoneNum;
    private javax.swing.JLabel jlblIc;
    private javax.swing.JLabel jlblSchedule;
    private javax.swing.JLabel jlblSearch;
    private javax.swing.JLabel jlblTimeSlot;
    private javax.swing.JLabel jlbmins;
    private javax.swing.JPanel jpAdd;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JTable jtSchedule;
    private javax.swing.JTextField jtfCusName;
    private javax.swing.JTextField jtfCusPhoneNum;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfStafIc;
    private javax.swing.JTextField jtfTimeSlotNum;
    // End of variables declaration//GEN-END:variables
}
