/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.MaintainService;
import domain.Service;
import domain.Staff;
import domain.TableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cheng
 */
public class ServicePanel extends javax.swing.JPanel {

    MaintainService serviceControl; 
    
    /**
     * Creates new form Service
     */
    public void setDynamicPanel() {
        JPanel targetPanel = new JPanel();
        if(MainMenu.action.equals("add")){
             targetPanel=jpAdd;
        }
        else if (MainMenu.action.equals("search")){
            targetPanel=jpSearch;
        }
        
        dynamicPanel.removeAll();
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
            
        //Adding Pannel
        dynamicPanel.add(targetPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }
        
    public ServicePanel() {
        initComponents();
        serviceControl = new MaintainService();
        jtfSearch.setOpaque(false);
        jtfSearch.setBackground(new Color(255,255,255,127));
        jtfSearch.setBorder(null);
        setDynamicPanel();
    }
    
    public Service validateInput(){
    
    Service service;
    boolean valid =true; 
    
    Double price = Double.parseDouble(jtfPrice.getText());
    String serviceid = jtfServiceId.getText();
    String title = jtfTitle.getText();
    String descrip = jtaDescrip.getText();
    
    valid = price.equals(null)?false:true; //need
    valid = serviceid.equals(null)?false:true;
    valid = title.equals(null)?false:true;
    valid = descrip.equals(null)?false:true;
    
    if(valid==true){
         
           // take object domain constructor and initialiue (pass value) 
           service = new Service(serviceid, title, price, descrip);
         }
         else {
             service=null;
         }
         
         return service;
    }
    
    
    
    public void resetFields(){
    
    jtfPrice.setText("");
    jtfSearch.setText("");
    jtfServiceId.setText("");
    jtfTitle.setText("");
    jtaDescrip.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        dynamicPanel = new javax.swing.JPanel();
        jpSearch = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtService = new javax.swing.JTable();
        jtfModifyService = new javax.swing.JButton();
        jtfDeleteService = new javax.swing.JButton();
        jpAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfServiceId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescrip = new javax.swing.JTextArea();
        jbtAddService = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(229, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 260, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 70));

        dynamicPanel.setLayout(new java.awt.CardLayout());

        jpSearch.setBackground(new java.awt.Color(229, 204, 255));
        jpSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service ID", "Title", "Unitn Price", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtService);

        jpSearch.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 550, 280));

        jtfModifyService.setText("Modify Service");
        jtfModifyService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfModifyServiceMouseClicked(evt);
            }
        });
        jtfModifyService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModifyServiceActionPerformed(evt);
            }
        });
        jpSearch.add(jtfModifyService, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jtfDeleteService.setText("Delete Service");
        jtfDeleteService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfDeleteServiceMouseClicked(evt);
            }
        });
        jpSearch.add(jtfDeleteService, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        dynamicPanel.add(jpSearch, "card3");

        jpAdd.setBackground(new java.awt.Color(229, 204, 255));
        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Service ID :");
        jpAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jtfServiceId.setToolTipText("Enter service ID");
        jpAdd.add(jtfServiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 90, -1));

        jLabel3.setText("Service Title :");
        jpAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jtfPrice.setToolTipText("Enter price");
        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });
        jpAdd.add(jtfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 70, -1));

        jLabel4.setText("Unit Price (RM) :");
        jpAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jtfTitle.setToolTipText("Enter service title");
        jtfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTitleActionPerformed(evt);
            }
        });
        jpAdd.add(jtfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 290, -1));

        jLabel5.setText("Service Description:");
        jpAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jtaDescrip.setColumns(20);
        jtaDescrip.setRows(5);
        jScrollPane1.setViewportView(jtaDescrip);

        jpAdd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 290, 120));

        jbtAddService.setText("Add Service");
        jbtAddService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddServiceMouseClicked(evt);
            }
        });
        jpAdd.add(jbtAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        dynamicPanel.add(jpAdd, "card2");

        jPanel1.add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 970, 480));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 970, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void jtfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTitleActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jtfModifyServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModifyServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModifyServiceActionPerformed

    private void jbtAddServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddServiceMouseClicked
        // TODO add your handling code here:
        Service service = validateInput();
        if(service!=null){
         //write to database
         Service s = serviceControl.searchRecord(service.getServiceID());
                
         if(s != null)
          {
                    JOptionPane.showMessageDialog(null,"This staff already exist.", "Duplicate Record", JOptionPane.ERROR_MESSAGE);
          }
         else
         {
                    s = service;
                    try{
                    serviceControl.addRecord(s);
                    resetFields();
                    JOptionPane.showMessageDialog(null,"New service is created.","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch (Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                    }
          }  
                
         
        }
        else{
            int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
                resetFields();
            }              
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddServiceMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //I used all my 洪荒之力 to make this method 

        jtService.setModel(new DefaultTableModel());
        jtService.repaint();
        String queryStr =jtfSearch.getText();
        int option =0;
        

            if(Pattern.matches("\\d{12}", queryStr)){
                option=1;
            }
            
            else{
                option=2;
            }
            ArrayList<Service> serviceList = serviceControl.searchRecord(queryStr,option);

    //        MainMenu.action="search";
    //        setDynamicPanel();
            if(serviceList.size()!=0||serviceList!=null){
                Object[][] data = new Object[100][8];
                for(int i=0; i<serviceList.size();i++){
                data[i] = serviceList.get(i).getObjects();
                } 
                String[] columnNames = {"Staff IC","Name","Address","Phone No","Position","Qualification"};
                TableModel tModel = new TableModel(data, columnNames);
                jtService.setModel(tModel);  
                jtService.createDefaultColumnsFromModel();
                jtService.repaint();
            }
            else{
                JOptionPane.showMessageDialog(null, "No results found!" , "No such record.", JOptionPane.ERROR_MESSAGE);
            }     
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jtfModifyServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfModifyServiceMouseClicked
        // TODO add your handling code here:
        MainMenu.action="modify";
       Service selectedService=null;
       if(jtService.getSelectedRow()>=0 ) {
           String ic  = (String) jtService.getValueAt(jtService.getSelectedRow(),0);
           selectedService = serviceControl.searchRecord(ic);
            
       }
       else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to modify","Empty selection",JOptionPane.ERROR_MESSAGE);
       }

    }//GEN-LAST:event_jtfModifyServiceMouseClicked

    private void jtfDeleteServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfDeleteServiceMouseClicked
        // TODO add your handling code here:
         MainMenu.action="delete";
       Service selectedService=null;
       if(jtService.getSelectedRow()>=0 ) {
           String ic  = (String) jtService.getValueAt(jtService.getSelectedRow(),0);
           selectedService = serviceControl.searchRecord(ic);
            
       }
       else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to delete","Empty selection",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jtfDeleteServiceMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAddService;
    private javax.swing.JPanel jpAdd;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JTable jtService;
    private javax.swing.JTextArea jtaDescrip;
    private javax.swing.JButton jtfDeleteService;
    private javax.swing.JButton jtfModifyService;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfServiceId;
    private javax.swing.JTextField jtfTitle;
    // End of variables declaration//GEN-END:variables
}
