/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.MaintainPet;
import control.MaintainService;
import control.MaintainStaff;
import control.MaintainTransaction;
import control.MaintainTransactionService;
import domain.Pet;
import domain.Service;
import domain.ServiceDetail;
import domain.Staff;
import domain.TableModel;
import domain.Transaction;
import java.awt.Color;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cheng
 */
public class TransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransactionPanel
     */
    private MaintainTransaction transControl;
    private MaintainService serviceControl;
    private MaintainStaff staffControl;
    private MaintainPet petControl;
    private MaintainTransactionService transServControl;
    private ArrayList<ServiceDetail> servList;
    private String action;
    private AddServiceDialog asd;
    private static ServiceDetail serviceDetail;

    public static void setService(ServiceDetail service) {
        TransactionPanel.serviceDetail = service;
    }
    
    public TransactionPanel() {
        initComponents();
        transControl = new MaintainTransaction();
        serviceControl = new MaintainService ();
        staffControl = new MaintainStaff();
        petControl = new MaintainPet();
        transServControl = new MaintainTransactionService();
        servList = new ArrayList<ServiceDetail>();
        serviceDetail=null;
        jtfSearch.setOpaque(false);
        jtfSearch.setBackground(new Color(255,255,255,127));
        jtfSearch.setBorder(null);
        setDynamicPanel();
    }

    public void resetFields(){
         
         jtfPetId.setText("");
         jtfSearch.setText("");
         jtService.setModel(new DefaultTableModel());
         jtService.repaint();
         
      for(int i=0; i<servList.size();i++){
         servList.remove(i);
       }
    
     
     }
     
    public ArrayList<ServiceDetail> getServList() {
        return servList;
    }

    public void setServList(ArrayList<ServiceDetail> servList) {
        this.servList = servList;
    }
    
    public boolean addService (ServiceDetail serviceD){
        boolean valid =true;
        for(int i=0; i<servList.size();i++){
           if(servList.get(i).getService().getServiceID().equals(serviceD.getService().getServiceID())){
               valid=false;
           }
        }
        if(valid){
            servList.add(serviceD);
        }
        
        return valid;
    }
    
    public void editService(ServiceDetail serviceD){
        for(int i=0; i<servList.size();i++){
           if(servList.get(i).getService().getServiceID().equals(serviceD.getService().getServiceID())){
               servList.remove(i);
               servList.add(i, serviceD);
           }
        }
    }
    
    public void removeService(ServiceDetail serviceD){
    for(int i=0; i<servList.size();i++){
       if(servList.get(i).getService().getServiceID().equals(serviceD.getService().getServiceID())){
           servList.remove(i);
       }
    }
}
    
    public void setDynamicPanel() {
        JPanel targetPanel = new JPanel();
        jtfTransId.setEnabled(false);
        if(MainMenu.action.equals("add")){
             targetPanel=jpAdd;
             jtfTransId.setText(generateTransId());
             
        }
        else if (MainMenu.action.equals("search")||MainMenu.action.equals("modify")||MainMenu.action.equals("delete")){
            targetPanel=jpTrans1;
        }
        
        dynamicPanel.removeAll();
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
            
        //Adding Pannel
        dynamicPanel.add(targetPanel);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }
    
    public String generateTransId(){
        ArrayList<Transaction> transList = transControl.searchRecord("", 0);
        
        //implement sorting 
        
        String idStr = transList.get(transList.size()-1).getTransID();
        int idNo = Integer.parseInt(idStr.split("T")[1])+1;
        
        return "T"+idNo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlblSearch = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jlblTrans = new javax.swing.JLabel();
        dynamicPanel = new javax.swing.JPanel();
        jpAdd = new javax.swing.JPanel();
        jlblTransId = new javax.swing.JLabel();
        jtfTransId = new javax.swing.JTextField();
        jlblTransDate = new javax.swing.JLabel();
        jlblTransTime = new javax.swing.JLabel();
        jlblPetID = new javax.swing.JLabel();
        jtfPetId = new javax.swing.JTextField();
        jdpTransDate = new com.toedter.calendar.JDateChooser();
        jcbHours = new javax.swing.JComboBox<>();
        jcbMins = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtService = new javax.swing.JTable();
        jbtRemoveService = new javax.swing.JButton();
        jbtAddService = new javax.swing.JButton();
        jbtEditService = new javax.swing.JButton();
        jbtAddTrans = new javax.swing.JButton();
        jbtRefresh = new javax.swing.JButton();
        jbtConfirmChange = new javax.swing.JButton();
        jbtConfirmDelete = new javax.swing.JButton();
        jpTrans1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTransList = new javax.swing.JTable();
        jbtModifyTrans = new javax.swing.JButton();
        jbtDeleteTrans = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jlblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblSearchMouseClicked(evt);
            }
        });
        jPanel2.add(jlblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 260, 30));

        jlblTrans.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlblTrans.setText("Transaction");
        jPanel2.add(jlblTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        dynamicPanel.setLayout(new java.awt.CardLayout());

        jpAdd.setBackground(new java.awt.Color(255, 204, 204));
        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTransId.setText("Transaction ID :");
        jpAdd.add(jlblTransId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 87, 23));

        jtfTransId.setToolTipText("Enter transaction ID");
        jtfTransId.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpAdd.add(jtfTransId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, -1));

        jlblTransDate.setText("Transaction Date :");
        jpAdd.add(jlblTransDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlblTransTime.setText("Transaction Time :");
        jpAdd.add(jlblTransTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jlblPetID.setText("Pet ID :");
        jpAdd.add(jlblPetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jtfPetId.setToolTipText("Enter pet ID");
        jtfPetId.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpAdd.add(jtfPetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 90, 20));
        jpAdd.add(jdpTransDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, -1));

        jcbHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jcbHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHoursActionPerformed(evt);
            }
        });
        jpAdd.add(jcbHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jcbMins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jpAdd.add(jcbMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel6.setText("hours                  minutes");
        jpAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, 20));

        jtService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service", "Staff ", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtService.setColumnSelectionAllowed(true);
        jtService.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtService);
        jtService.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtService.getColumnModel().getColumnCount() > 0) {
            jtService.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtService.getColumnModel().getColumn(1).setPreferredWidth(20);
            jtService.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jpAdd.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 530, 190));

        jbtRemoveService.setText("Remove Service Item");
        jbtRemoveService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveServiceActionPerformed(evt);
            }
        });
        jpAdd.add(jbtRemoveService, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jbtAddService.setText("Add Service Item");
        jbtAddService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddServiceMouseClicked(evt);
            }
        });
        jbtAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddServiceActionPerformed(evt);
            }
        });
        jpAdd.add(jbtAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jbtEditService.setText("Edit Service Item");
        jbtEditService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditServiceActionPerformed(evt);
            }
        });
        jpAdd.add(jbtEditService, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jbtAddTrans.setText("Add transaction");
        jbtAddTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddTransActionPerformed(evt);
            }
        });
        jpAdd.add(jbtAddTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 110, -1));

        jbtRefresh.setText("Refresh");
        jbtRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRefreshActionPerformed(evt);
            }
        });
        jpAdd.add(jbtRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jbtConfirmChange.setText("Confirm Changes");
        jbtConfirmChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmChangeActionPerformed(evt);
            }
        });
        jpAdd.add(jbtConfirmChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jbtConfirmDelete.setText("Confirm Delete");
        jbtConfirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmDeleteActionPerformed(evt);
            }
        });
        jpAdd.add(jbtConfirmDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        dynamicPanel.add(jpAdd, "card3");

        jpTrans1.setBackground(new java.awt.Color(255, 204, 204));
        jpTrans1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtTransList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Date", "Time", "Pet ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTransList);

        jpTrans1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 570, 230));

        jbtModifyTrans.setText("Modify Transaction");
        jbtModifyTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtModifyTransMouseClicked(evt);
            }
        });
        jbtModifyTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifyTransActionPerformed(evt);
            }
        });
        jpTrans1.add(jbtModifyTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jbtDeleteTrans.setText("Delete Transaction");
        jbtDeleteTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtDeleteTransMouseClicked(evt);
            }
        });
        jpTrans1.add(jbtDeleteTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        dynamicPanel.add(jpTrans1, "card2");

        add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 960, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jcbHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHoursActionPerformed

    private void jbtRemoveServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveServiceActionPerformed
        // TODO add your handling code here:
        action="delete";
        if(jtService.getSelectedRow()>=0 ) {
          
           Service service = serviceControl.searchRecord((String) jtService.getValueAt(jtService.getSelectedRow(),0));
           Staff staff = staffControl.searchRecord((String) jtService.getValueAt(jtService.getSelectedRow(),1),2).get(0);
           
           ServiceDetail servD = new ServiceDetail();
           servD.setStaffIC(staff);
           servD.setService(service);
           removeService(servD);
           jbtRefreshActionPerformed(evt);
           JOptionPane.showMessageDialog(null,"Item deleted succesfully.","Success",JOptionPane.INFORMATION_MESSAGE);
       }
       else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to delete","Empty selection",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtRemoveServiceActionPerformed

    private void jbtAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddServiceActionPerformed
        // TODO add your handling code here:
        action="add";
        asd = new AddServiceDialog((JFrame)this.getParent().getParent().getParent().getParent().getParent().getParent(), false);
        asd.setVisible(true);
    }//GEN-LAST:event_jbtAddServiceActionPerformed

    private void jbtEditServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditServiceActionPerformed
        // TODO add your handling code here:
        action="edit";
        if(jtService.getSelectedRow()>=0 ) {
            String serviceID = (String) jtService.getValueAt(jtService.getSelectedRow(),0);
            String staffId =(String) jtService.getValueAt(jtService.getSelectedRow(),1);
            String remarks = (String) jtService.getValueAt(jtService.getSelectedRow(),2);
            
            asd = new AddServiceDialog((JFrame)this.getParent().getParent().getParent().getParent().getParent().getParent(), false);
            asd.fillFields(serviceID, staffId, remarks);
            asd.setVisible(true);   
        }
        else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to modify","Empty selection",JOptionPane.ERROR_MESSAGE);
       }
        
        
            
    }//GEN-LAST:event_jbtEditServiceActionPerformed

    private void jbtModifyTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifyTransActionPerformed
        // TODO add your handling code here:
 

    }//GEN-LAST:event_jbtModifyTransActionPerformed

    private void jbtAddServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddServiceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddServiceMouseClicked

    private void jlblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSearchMouseClicked
        // TODO add your handling code here:
        //I used all my 洪荒之力 to make this method 
        ///// jtService is jttransList
        jtTransList.setModel(new DefaultTableModel());
        jtTransList.repaint();
        
        if(MainMenu.action == "modifySelected"){
            MainMenu.action="modify";
        }
        else if(MainMenu.action == "deleteSelected"){
            MainMenu.action="delete";
        }
        String queryStr =jtfSearch.getText();
        int option =0;
        

            if(Pattern.matches("\\d{12}", queryStr)){
                option=1;
            }
            
            else{
                option=2;
            }
            ArrayList<Transaction> transactionList = transControl.searchRecord(queryStr,option);

//            MainMenu.action="search";
//            setDynamicPanel();
            if(transactionList.size()!=0&&transactionList!=null){
                Object[][] data = new Object[100][8];
                for(int i=0; i<transactionList.size();i++){
                data[i] = transactionList.get(i).getObjects();
                } 
                String[] columnNames = {"Service","Staff","Remarks"};
                TableModel tModel = new TableModel(data, columnNames);
                jtTransList.setModel(tModel);  
                jtTransList.createDefaultColumnsFromModel();
                jtTransList.repaint();
            }
            else{
                JOptionPane.showMessageDialog(null, "No results found!" , "No such record.", JOptionPane.ERROR_MESSAGE);
            }     
    }//GEN-LAST:event_jlblSearchMouseClicked

    private void jbtDeleteTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtDeleteTransMouseClicked
        // TODO add your handling code here:
        MainMenu.action="delete";
       Transaction selectedTrans=null;
       ArrayList<ServiceDetail> servList = new ArrayList<ServiceDetail>();
       if(jtTransList.getSelectedRow()>=0 ) {
           String id  = (String) jtTransList.getValueAt(jtTransList.getSelectedRow(),0);
           selectedTrans = transControl.searchRecord(id);
           servList = transServControl.searchRecord(id, 1);
           // fillFields(trans serv);
       }
       else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to modify","Empty selection",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtDeleteTransMouseClicked

    private void jbtModifyTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtModifyTransMouseClicked
        // TODO add your handling code here:
       MainMenu.action="modify";
       Transaction selectedTrans=null;
       ArrayList<ServiceDetail> servList = new ArrayList<ServiceDetail>();
       if(jtTransList.getSelectedRow()>=0 ) {
           String id  = (String) jtTransList.getValueAt(jtTransList.getSelectedRow(),0);
           selectedTrans = transControl.searchRecord(id);
           servList = transServControl.searchRecord(id, 1);
           // fillFields(trans serv);
       }
       else{
           JOptionPane.showMessageDialog(null,"Please search and select the record you wish to modify","Empty selection",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtModifyTransMouseClicked

    private void jbtAddTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddTransActionPerformed
        // TODO add your handling code here:
        Transaction trans = validateInput();
        
        if(trans!=null){
            Transaction t = transControl.searchRecord(trans.getTransID());
                
                if(t != null)
                {
                    JOptionPane.showMessageDialog(null,"This transaction already exist.", "Duplicate Record", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    t = trans;
                    try{
                    transControl.addRecord(t);
                    transServControl.addRecord(t);
                    resetFields();
                    JOptionPane.showMessageDialog(null,"New transaction has been created.","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch (Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                    }
                }  
        }
        else{
        int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
                resetFields();
            }
        }

    }//GEN-LAST:event_jbtAddTransActionPerformed

    private void jbtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRefreshActionPerformed
        // TODO add your handling code here:
        //check if null 
        jtService.setModel(new DefaultTableModel());
        jtService.repaint();
        if(serviceDetail!=null){
            if(action=="add"||action=="edit"){
                if(addService(serviceDetail)==false){
                    int option = JOptionPane.showConfirmDialog(null, "This service already exists. Are you sure you want to overwrite it?", "Overwrite service details?", JOptionPane.YES_NO_OPTION);
                    if(option==JOptionPane.YES_OPTION){
                        editService(serviceDetail);
                        JOptionPane.showMessageDialog(null,"Service item edited successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else    {
                    JOptionPane.showMessageDialog(null,"Service item added succesfully","Success",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
           if(servList.size()!=0&&servList!=null){
                Object[][] data = new Object[100][8];
                for(int i=0; i<servList.size();i++){
                    data[i] = servList.get(i).getObjects();
                } 
                String[] columnNames = {"Service","Staff","Remarks"};
                TableModel tModel = new TableModel(data, columnNames);
                jtService.setModel(tModel);  
                jtService.createDefaultColumnsFromModel();
                jtService.repaint();
            }
        }
        else{
        
            JOptionPane.showMessageDialog(null,"No item found!","Error",JOptionPane.ERROR_MESSAGE);
        }
        System.out.print(serviceDetail.getRemarks());
    }//GEN-LAST:event_jbtRefreshActionPerformed

    private void jbtConfirmChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmChangeActionPerformed
        // TODO add your handling code here:
        Transaction transaction = validateInput();
        if(transaction!=null){
         //write to database ****
                Transaction t = transControl.searchRecord(transaction.getTransID());
                
                if(t == null)
                {
                    JOptionPane.showMessageDialog(null,"This transaction does not exist.", "Record Not Found", JOptionPane.ERROR_MESSAGE);
                }
                else
                {                
                    int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Are you sure you want commit the changes made?", "Confirm changes?", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
                    if(reply==JOptionPane.YES_OPTION){
                        try{
                            transControl.updateRecord(t);
                            transServControl.updateRecord(t);
                            resetFields();
                            JOptionPane.showMessageDialog(null,"Transaction details "+ t.getTransID()+" has been updated.","Success",JOptionPane.INFORMATION_MESSAGE);
                        }
                        catch (Exception ex){
                            JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                
                //---*****
        }
        else{
            //****
            int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
                resetFields();
            }
            //***
        }
    }//GEN-LAST:event_jbtConfirmChangeActionPerformed

    private void jbtConfirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmDeleteActionPerformed
        // TODO add your handling code here:
        Transaction transaction = validateInput();
        if(transaction!=null){
         //write to database ****
                Transaction t = transControl.searchRecord(transaction.getTransID());
                
                if(t == null)
                {
                    JOptionPane.showMessageDialog(null,"This transaction does not exist.", "Record Not Found", JOptionPane.ERROR_MESSAGE);
                }
                else
                {                
                    int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Are you sure you want commit the changes made?", "Confirm changes?", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
                    if(reply==JOptionPane.YES_OPTION){
                        try{
                            transServControl.deleteRecord(t.getTransID());
                            transControl.deleteRecord(t.getTransID());
                            
                            resetFields();
                            JOptionPane.showMessageDialog(null,"Transaction details "+ t.getTransID()+" has been updated.","Success",JOptionPane.INFORMATION_MESSAGE);
                        }
                        catch (Exception ex){
                            JOptionPane.showMessageDialog(null,ex.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                
                //---*****
        }
        else{
            //****
            int reply =JOptionPane.showConfirmDialog(this.getParent().getParent().getParent(), "Your input seems to have data that is invalid or in incorrect format. Would you like to reset all fields?", "Invalid Data!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(reply==JOptionPane.YES_OPTION){
                resetFields();
            }
            //***
        }
        
    }//GEN-LAST:event_jbtConfirmDeleteActionPerformed

    public Transaction validateInput(){
        
        boolean valid = true;
        Transaction transaction = null;
        int hours  = Integer.parseInt((String)jcbHours.getSelectedItem());
        int minutes = Integer.parseInt((String)jcbMins.getSelectedItem());
        long milliseconds = (minutes * 60000)+ (hours * 3600000)-(30 * 60000)- (7 * 3600000);
        Time transTime = new Time(milliseconds);
        
        Date transDate = jdpTransDate.getDate();
        String petID = jtfPetId.getText();
        Pet pet = petControl.searchRecord(petID);
        String transID = jtfTransId.getText(); //auto gen
        
        if(pet==null){
            valid=false;
        }
        if(valid){
            transaction = new Transaction (transID, transDate, transTime, pet, servList);
        }
        else{
            transaction = null;
        }
        
        return transaction;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAddService;
    private javax.swing.JButton jbtAddTrans;
    private javax.swing.JButton jbtConfirmChange;
    private javax.swing.JButton jbtConfirmDelete;
    private javax.swing.JButton jbtDeleteTrans;
    private javax.swing.JButton jbtEditService;
    private javax.swing.JButton jbtModifyTrans;
    private javax.swing.JButton jbtRefresh;
    private javax.swing.JButton jbtRemoveService;
    private javax.swing.JComboBox<String> jcbHours;
    private javax.swing.JComboBox<String> jcbMins;
    private com.toedter.calendar.JDateChooser jdpTransDate;
    private javax.swing.JLabel jlblPetID;
    private javax.swing.JLabel jlblSearch;
    private javax.swing.JLabel jlblTrans;
    private javax.swing.JLabel jlblTransDate;
    private javax.swing.JLabel jlblTransId;
    private javax.swing.JLabel jlblTransTime;
    private javax.swing.JPanel jpAdd;
    private javax.swing.JPanel jpTrans1;
    private javax.swing.JTable jtService;
    private javax.swing.JTable jtTransList;
    private javax.swing.JTextField jtfPetId;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfTransId;
    // End of variables declaration//GEN-END:variables

    public static ServiceDetail getService() {
        return serviceDetail;
    }
}
