/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Cheng
 */
public class TransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransactionPanel
     */
    public TransactionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jpSearch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setToolTipText("search by NRIC or Name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 240, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 960, 103));

        jPanel1.setLayout(new java.awt.CardLayout());

        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Transaction ID :");
        jpAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 59, 87, 23));

        jTextField2.setToolTipText("Enter transaction ID");
        jpAdd.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 60, 71, -1));

        jLabel3.setText("Transaction Date :");
        jpAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 63, -1, -1));

        jLabel4.setText("Transaction Time :");
        jpAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 100, -1, -1));

        jLabel5.setText("Pet ID :");
        jpAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 100, -1, -1));

        jTextField3.setToolTipText("Enter pet ID");
        jpAdd.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 80, -1));

        jPanel1.add(jpAdd, "card3");

        jpSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Date", "Time", "Pet ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jpSearch.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 140));

        jPanel1.add(jpSearch, "card2");

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 960, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel jpAdd;
    private javax.swing.JPanel jpSearch;
    // End of variables declaration//GEN-END:variables
}
