SELECT
     TRANSACTION1."TRANSID" AS TRANSACTION1_TRANSID,
     TRANSACTION1."TRANSDATE" AS TRANSACTION1_TRANSDATE,
     TRANSACTION1."TRANSTIME" AS TRANSACTION1_TRANSTIME,
     PAYMENT."PAYMENTID" AS PAYMENT_PAYMENTID,
     PAYMENT."AMOUNTPAID" AS PAYMENT_AMOUNTPAID,
     PAYMENT."PAYMENTDATE" AS PAYMENT_PAYMENTDATE,
     PAYMENT."STAFFIC" AS PAYMENT_STAFFIC,
     CUSTOMER."CUSTIC" AS CUSTOMER_CUSTIC
FROM
     "NBUSER"."TRANSACTION1" TRANSACTION1 INNER JOIN "NBUSER"."PAYMENT" PAYMENT ON TRANSACTION1."TRANSID" = PAYMENT."TRANSID"
     INNER JOIN "NBUSER"."PET" PET ON TRANSACTION1."PETID" = PET."PETID"
     INNER JOIN "NBUSER"."CUSTOMER" CUSTOMER ON PET."CUSTIC" = CUSTOMER."CUSTIC"